baseURL = "https://pulumi.io/"
languageCode = "en-us"
title = "Pulumi"

sectionPagesMenu = "main"

pygmentsCodefences = true
pygmentsUseClasses = true

[params]
    repositoryURL = "https://github.com/pulumi/docs"
    repositoryBranch = "master"