baseURL = "https://pulumi.io/"
languageCode = "en-us"
title = "Pulumi"

disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS"]

pygmentsCodefences = true
pygmentsUseClasses = true

[params]
    repositoryURL = "https://github.com/pulumi/docs"
    repositoryBranch = "master"
